{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    control-plane: controller-manager
    {{- include "network-policy-generator.labels" . | nindent 4 }}
{{- end }}
