# permissions for end users to view networkpolicygenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-policy-generator
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicygenerator-viewer-role
rules:
- apiGroups:
  - security.policy.io
  resources:
  - networkpolicygenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.policy.io
  resources:
  - networkpolicygenerators/status
  verbs:
  - get
