apiVersion: security.policy.io/v1
kind: NetworkPolicyGenerator
metadata:
  name: test-cilium-allow
  labels:
    app.kubernetes.io/name: network-policy-generator
    app.kubernetes.io/managed-by: kustomize
spec:
  mode: "enforcing"
  policyEngine: "cilium"

  policy:
    type: "allow"
    deniedNamespaces:
      - "test-ns1"
      - "test-ns2"

  globalRules:
    - type: "allow"
      port: 80
      protocol: TCP
      direction: "ingress"
    - type: "allow"
      port: 443
      protocol: TCP
      direction: "egress"
