apiVersion: security.policy.io/v1
kind: NetworkPolicyGenerator
metadata:
  name: test-policy-generator-allow
  labels:
    app.kubernetes.io/name: network-policy-generator
    app.kubernetes.io/managed-by: kustomize
spec:
  mode: "enforcing"  # learning or enforcing
  # duration: "1m"     # required when mode is learning
  
  policy:
    type: "allow"     # allow or deny
    # allowedNamespaces:     # used when type is deny
    #   - "test-ns1"
    #   - "test-ns2"
    deniedNamespaces:      # used when type is allow
      - "test-ns1"
      - "test-ns2"
    
  globalRules:       # consolidated global rules
    - type: "allow"  # allow or deny
      port: 80
      protocol: TCP
      direction: "ingress"  # ingress or egress
    - type: "allow"
      port: 443
      protocol: TCP
      direction: "egress"
