apiVersion: security.policy.io/v1
kind: NetworkPolicyGenerator
metadata:
  name: test-policy-generator
  labels:
    app.kubernetes.io/name: network-policy-generator
    app.kubernetes.io/managed-by: kustomize
spec:
  mode: "enforcing"  # learning 또는 enforcing
  duration: "1m"     # learning 모드일 때만 사용
  
  policy:
    type: "deny"     # allow 또는 deny
    allowedNamespaces:     # deny 타입일 때 사용
      - "test-ns1"
      - "test-ns2"
    deniedNamespaces:      # allow 타입일 때 사용
      - "test-ns3"
      - "test-ns4"
    
  globalRules:       # 글로벌 규칙 통합
    - type: "allow"  # allow 또는 deny
      port: 80
      protocol: TCP
      direction: "ingress"  # ingress 또는 egress
    - type: "allow"
      port: 443
      protocol: TCP
      direction: "egress"
