apiVersion: security.policy.io/v1
kind: NetworkPolicyGenerator
metadata:
  name: test-policy-generator-deny
  namespace: test-ns1
spec:
  mode: "enforcing"
  policy:
    type: "deny"
    allowedNamespaces:
      - "test-ns3"  # reachable only from test-ns3
  globalRules:
    - type: "allow"
      port: 80
      protocol: TCP
      direction: "ingress"
---
apiVersion: security.policy.io/v1
kind: NetworkPolicyGenerator
metadata:
  name: test-policy-generator-deny
  namespace: test-ns2
spec:
  mode: "enforcing"
  policy:
    type: "deny"
    allowedNamespaces: []  # block all access
  globalRules: []  # drop the global rules as well
