# Example: Cilium Deny Policy
# helm install npg ./helm/network-policy-generator -f ./helm/network-policy-generator/values/cilium-deny-values.yaml

image:
  repository: somaz940/network-policy-generator
  tag: v0.0.3
